version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'devices'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
  spring-device:
    hostname: spring-device
    container_name: spring-device
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_IP=db
      - DB_PORT=3306
      - DB_DBNAME=devices
      - DB_USER=root
      - DB_PASSWORD=admin
    networks:
      demo_net:
volumes:
  my-db:

networks:
  demo_net:
    external: true
